eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://service-registry:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
